language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
env:
  global:
    secure: gJXJmJTN5xJv3pBBvwbSYLjJPwakAXXkkxAHPaqUSngEWCtNaNj5aeRC0Jjje4Vx5jV6S7rfsO77h1WNMZVR2iNng60p5yQjNGwkLaVIF8Lu6QridM3D+LM285E2NJ450OSa4OKOCxEA50akGNPe3QR38aDVl9ZvFSJupyWFRI8=
after_success:
- bash .travis/after_success
